# Generated by Django 4.2.4 on 2024-12-30 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_todo_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='completed',
        ),
    ]
